### PR TITLE
Instructions for using Vagrant on OSX

### PR DESCRIPTION
**Pull request by alsuren**
My primary development machine is a mac, so I can't use the linux-specific instructions. I was following a lot of tricks from these posts:

https://dev.to/kojikanao/coral-edgetpu-usb-with-virtualbox-57e1
https://sonnguyen.ws/connect-usb-from-virtual-machine-using-vagrant-and-virtualbox/

Hopefully this makes life easier for everyone.

I was using this to test that my setup steps were reproducible:
```
vagrant destroy --force && vagrant up && vagrant reload && vagrant ssh
...
cd ~/project-posenet && python3 simple_pose.py
```

### CODE REVIEW

**Comment by alsuren** [comment]
@googlebot I signed it!

**Comment by mtyka** [comment]
Apologies for missing this for so long - it slipped past my notifications. 
This is super awesome - but a lot more general than just for posenet. I suggest we actually put this into  **https://github.com/google-coral/edgetpu-platforms** - what do you think ?

**Comment by alsuren** [comment]
In order to generalise it, we would need to:
- remove the hard coded ~/project-posenet mount point and replace it with something better (vagrant used to give you a /vagrant mount point by default, but it didn't work for me on my first attempt so I hacked around it)
- find a way to phrase the instructions in this repo to point to the Vagrantfile in the other repo (usually the Vagrantfile lives in the same repo as the code, but we have multiple repos so I'm not sure what to do there)
- find a way to avoid copy-pasting the Vagrantfile around with minor changes into all of the repos

I will need to load this back into my head in order to address these points. I will try to do so in the next few weeks, but I'm currently applying for jobs, so I make no guarantees.

**Comment by alsuren** [comment]
closed in favour of https://github.com/google-coral/edgetpu-platforms/pull/20

**Pull request closed without merging**
